### ISSUE TITLE
Problem installing matplotlib

### ISSUE THREAD

**Issue by tcsaba101** [MGX3D/CurrentViewer#1]
Hi,
I am not very experienced in py, this is the error message:

C:\Users\User\Documents\CR_Dev>pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyserial in c:\users\user\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 1)) (3.4)
Collecting matplotlib
  Using cached matplotlib-3.3.2.tar.gz (37.9 MB)
Collecting mplcursors
  Using cached mplcursors-0.3-py3-none-any.whl (18 kB)
Requirement already satisfied: certifi>=2020.06.20 in c:\users\user\appdata\roaming\python\python39\site-packages (from matplotlib->-r requirements.txt (line 2)) (2020.6.20)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\roaming\python\python39\site-packages (from matplotlib->-r requirements.txt (line 2)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from matplotlib->-r requirements.txt (line 2)) (1.3.1)
Requirement already satisfied: numpy>=1.15 in c:\users\user\appdata\roaming\python\python39\site-packages (from matplotlib->-r requirements.txt (line 2)) (1.19.4)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from matplotlib->-r requirements.txt (line 2)) (8.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\user\appdata\roaming\python\python39\site-packages (from matplotlib->-r requirements.txt (line 2)) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from matplotlib->-r requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: six in c:\users\user\appdata\roaming\python\python39\site-packages (from cycler>=0.10->matplotlib->-r requirements.txt (line 2)) (1.15.0)
Using legacy 'setup.py install' for matplotlib, since package 'wheel' is not installed.
Installing collected packages: matplotlib, mplcursors
    Running setup.py install for matplotlib ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-vl14nkmy\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-vl14nkmy\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-m_564wc1\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\User\AppData\Roaming\Python\Python39\Include\matplotlib'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-vl14nkmy\matplotlib\
    Complete output (571 lines):

Please advise what to change.

Thanks, Csaba

**Comment by MGX3D** [comment]
This seems to be an issue with Python 3.9 and matplotlib (and some other packages). It appears the temporary workaround is to switch to Python 3.8
